In [4]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [13]:
df = pd.read_csv("/home/somitemp/Kuliah/Semester 8/Data Warehouse/Proyek/STG_EHP_DATASET/STG_EHP__INVN/STG_EHP__INVN_1_1.csv")
df

,MAT_SKU,INGTN_TS,OPEN_QTY,OPEN_STF,RCVD_QTY,RCVD_STF,ISSD_QTY,ISSD_STF,CLSD_QTY,CLSD_STF,VRFC_STF
0,A0A286718,2025-01-01,1100.0,7697I,0.0,7979P,1,6660S,1099.0,4071N,6311W
1,A0A286718,2025-01-02,1099.0,7511Y,0.0,1236B,2,4642B,1097.0,8659B,2505R
2,A0A286718,2025-01-03,1097.0,8187E,0.0,3084J,3,4108I,1094.0,2419L,8366F
3,A0A286718,2025-01-04,1094.0,2907B,0.0,5555S,2,1246G,1092.0,7703U,4094B
4,A0A286718,2025-01-05,1092.0,3540T,0.0,2325F,5,8340N,1087.0,8761L,3801I
...,...,...,...,...,...,...,...,...,...,...,...
949995,A33S259765,2025-08-30,99.0,5452S,0.0,2860L,1,4300O,98.0,8834F,4620M
949996,A33S259765,2025-08-31,98.0,4992B,0.0,4838F,4,3915M,94.0,5802R,8024X
949997,A33S259765,2025-09-01,94.0,3189O,0.0,4071N,2,3124X,92.0,7722X,2362Z
949998,A33S259765,2025-09-02,92.0,2424V,0.0,2013X,0,7725I,92.0,6734E,5494L
949999,A33S259765,2025-09-03,92.0,2625S,0.0,2906Z,0,8377C,92.0,2727A,5995Z

In [12]:
df2 = pd.read_csv("/home/somitemp/Kuliah/Semester 8/Data Warehouse/Proyek/STG_EHP_DATASET/STG_EHP__INVN/STG_EHP__INVN_1_2.csv")
df2

,MAT_SKU,INGTN_TS,OPEN_QTY,OPEN_STF,RCVD_QTY,RCVD_STF,ISSD_QTY,ISSD_STF,CLSD_QTY,CLSD_STF,VRFC_STF
0,A33S259765,2025-09-04,92.0,4838B,0.0,1737I,1,5052O,91.0,6529N,4620M
1,A33S259765,2025-09-05,91.0,1390G,0.0,2218G,3,2783C,88.0,3234I,4620M
2,A33S259765,2025-09-06,88.0,5355Q,0.0,3738W,3,4931M,85.0,7349E,8543F
3,A33S259765,2025-09-07,85.0,5765H,0.0,6731L,1,6792K,84.0,7514X,4337Q
4,A33S259765,2025-09-08,84.0,5061J,0.0,3795G,2,4725F,82.0,4557Z,7072H
...,...,...,...,...,...,...,...,...,...,...,...
949995,A58L973514,2025-08-14,250.0,2161G,0.0,6537U,2,2623S,248.0,2409H,8174X
949996,A58L973514,2025-08-15,248.0,8609F,0.0,3404V,5,6382Q,243.0,7589Y,1392B
949997,A58L973514,2025-08-16,243.0,5326H,0.0,8371Y,2,5910W,241.0,6809S,2248J
949998,A58L973514,2025-08-17,241.0,5664E,0.0,8386F,0,2842X,241.0,3330X,6151D
949999,A58L973514,2025-08-18,241.0,6555N,0.0,7053R,4,2715K,237.0,7668D,1411Q

In [15]:
df3 = pd.read_csv("STG_EHP_DATASET/STG_EHP__INVN/STG_EHP__INVN_6_18.csv")
df3

,MAT_SKU,INGTN_TS,OPEN_QTY,OPEN_STF,RCVD_QTY,RCVD_STF,ISSD_QTY,ISSD_STF,CLSD_QTY,CLSD_STF,VRFC_STF
0,Z65G118492,2025-01-17,1062.0,3113I,0.0,6582I,4,4217N,1058.0,6795U,2133V
1,Z65G118492,2025-01-18,1058.0,6892R,0.0,1264Q,1,7538Q,1057.0,1658V,2682F
2,Z65G118492,2025-01-19,1057.0,5640E,0.0,1314E,2,6631Q,1055.0,6660N,1407Q
3,Z65G118492,2025-01-20,1055.0,7847I,0.0,2735Z,4,2988Y,1051.0,4685U,5752Y
4,Z65G118492,2025-01-21,1051.0,8333N,0.0,2378H,0,7072H,1051.0,1909L,2791N
...,...,...,...,...,...,...,...,...,...,...,...
949995,Z8Q455799,2025-09-17,9.0,8593M,0.0,2200U,0,5758G,9.0,7757K,4381B
949996,Z8Q455799,2025-09-18,9.0,3406Y,0.0,1307W,0,8854R,9.0,7898P,7265A
949997,Z8Q455799,2025-09-19,9.0,4751C,0.0,4084V,5,7179I,4.0,2009V,4521F
949998,Z8Q656656,2025-01-01,1150.0,6532X,0.0,8518J,3,7350G,1147.0,8446Y,5901T
949999,Z8Q656656,2025-01-02,1147.0,6807Y,0.0,1743Z,3,1798Q,1144.0,6203H,7458V

In [ ]:
df4 = pd.read_csv("/home/somitemp/Kuliah/Semester 8/Data Warehouse/Proyek/STG_EHP_DATASET/STG_EHP__INVN/STG_EHP__INVN_6_19.csv")
df4

,MAT_SKU,INGTN_TS,OPEN_QTY,OPEN_STF,RCVD_QTY,RCVD_STF,ISSD_QTY,ISSD_STF,CLSD_QTY,CLSD_STF,VRFC_STF
0,Z8Q656656,2025-01-03,1144.0,8462F,0.0,1504Y,4,5437E,1140.0,3059F,1390G
1,Z8Q656656,2025-01-04,1140.0,6358U,0.0,6503F,4,5969R,1136.0,7744U,5995Z
2,Z8Q656656,2025-01-05,1136.0,5547E,0.0,8193U,3,8333N,1133.0,8336L,3409E
3,Z8Q656656,2025-01-06,1133.0,5812C,0.0,2987P,4,7706S,1129.0,3169E,2623S
4,Z8Q656656,2025-01-07,1129.0,5117Y,0.0,2218E,2,3156A,1127.0,7643L,5664I
...,...,...,...,...,...,...,...,...,...,...,...
397447,Z9Z900387,2025-09-15,229.0,7499W,0.0,7514X,1,5981K,228.0,5980K,4640N
397448,Z9Z900387,2025-09-16,228.0,2409H,0.0,2682P,4,6349Y,224.0,7606L,1882C
397449,Z9Z900387,2025-09-17,224.0,3157T,0.0,4268L,0,8828Q,224.0,8733K,4161K
397450,Z9Z900387,2025-09-18,224.0,7160A,0.0,8762Z,2,3915M,222.0,2259U,8163Z
397451,Z9Z900387,2025-09-19,222.0,8128R,0.0,3252G,4,4991G,218.0,6430L,3964S